version: 2.1
orbs:
commands:
  destroy_environment:
    steps:
      - run:
          name:  Destroy infrastructure created by cloudformation
          when: on_fail
          command: aws cloudformation delete-stack --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5}
jobs:  
  create_infrastructure: 
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Create Cloudformation Stack
          command: |
            aws cloudformation deploy --template-file template.yml --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} --region us-east-1

  configure_infrastructure:
    docker:
      - image: python:3.11-rc-alpine   
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["2b:59:67:78:3e:32:06:1c:27:17:d9:3b:9d:67:e2:6a"]
      - run: 
          name: Install Ansible
          command: apk add --update ansible
      - run:
          name: Run Playbook and Configure server
          command: ansible-playbook -i inventory main.yml  

  smoke_test_test_website:
    docker:
      - image:  alpine:latest
    steps:
      - run:  apk add --update curl
      - run:
          name: smoke test
          command: |
            if curl -s --head https://blog.udacity.com/  
            then 
              return 1
            else 
              return 0
            fi
      - destroy_environment
  
  smoke_test:
    docker:
      - image:  amazon/aws-cli
    steps:
      - run:
          name: smoke test
          command: return 1
      - destroy_environment

workflows:
  myWorkflow:
    jobs:
      - create_infrastructure
      #- configure_infrastructure
      - smoke_test:
          requires:
            - create_infrastructure
