version: 2.1
commands:
  print_pipeline_id:
    description: "This prints the pipeline id"
    steps:
      - run: echo ${CIRCLE_WORKFLOW_ID}
jobs:
  save_hello_world_output:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo "hello world" > ~/output.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - output.txt

  print_output_file:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - attach_workspace:
          at: ~/
      - run: cat ~/output.txt

  use_commad:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - print_pipeline_id
  
  check_fail_job:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run:
          command: echo "Starting to fail job"
                   return 1
      - run:
          command: echo "Job failed!!!"
          when: on_fail
          
workflows:
  my_workflow:
    jobs:
      - save_hello_world_output
      - print_output_file:
          requires:
            - save_hello_world_output
      - use_commad
      - check_fail_job
